#!/bin/bash
# This file is part of: dtob (Version 1.0)
# Author: Chiayo Lin
# Date  : Nov. 02, 2014 

PGM_PATH=/usr/local/bin/
PGM_NAME=dtob

if [ -f $PGM_PATH$PGM_NAME ]
then
	echo "rm $PGM_PATH$PGM_NAME..."
	rm $PGM_PATH$PGM_NAME
	echo "$PGM_NAME successfully uninstalled :-)"
else
	echo "$PGM_NAME has not been installed yet!"
fi

exit 0
